version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: norte_gestion_dev
      POSTGRES_USER: norte_gestion
      POSTGRES_PASSWORD: norte_gestion123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U norte_gestion"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://norte_gestion:norte_gestion123@db:5432/norte_gestion_dev
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend,frontend
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: npm run dev

volumes:
  postgres_data:
  static_volume: