version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=motocenter.settings.development
      - SECRET_KEY=dev-secret-key-for-testing-only
      - DEBUG=True
    volumes:
      - ./db_local_test.sqlite3:/app/db_local_test.sqlite3
      - ./static:/app/staticfiles
      - ./media:/app/media
    command: >
      sh -c "echo '[LOCAL] Starting Django development server...' &&
             python manage.py collectstatic --noinput --clear &&
             python manage.py runserver 0.0.0.0:8000"
    networks:
      - local_network
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/api/')"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.production
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=/api
    networks:
      - local_network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/production.conf:/etc/nginx/conf.d/default.conf
      - ./static:/var/www/static:ro
      - ./media:/var/www/media:ro
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - local_network

networks:
  local_network:
    driver: bridge