version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "0.0.0.0:8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-development-key
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "0.0.0.0:3000:3000"
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    depends_on:
      - web