# Generated by Django 4.2.24 on 2025-09-09 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoteitem',
            name='servicio',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
