# Generated by Django 4.2.24 on 2025-09-12 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rubro',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='quoteitem',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='quoteitem',
            name='quote',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
        migrations.DeleteModel(
            name='QuoteItem',
        ),
        migrations.DeleteModel(
            name='Rubro',
        ),
    ]
